# Generated by Django 3.2.21 on 2024-01-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0003_auto_20240116_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
