# Generated by Django 3.2.21 on 2024-01-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0004_homevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('projects', models.PositiveSmallIntegerField(blank=True)),
                ('image', models.ImageField(upload_to='videographers/')),
            ],
        ),
    ]
