# Generated by Django 3.2.21 on 2024-01-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0005_videographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='videographer',
            name='slogen',
            field=models.TextField(blank=True),
        ),
    ]
