# Generated by Django 3.2.21 on 2024-01-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0008_auto_20240123_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='drive_link',
        ),
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/'),
        ),
    ]
