# Generated by Django 3.2.21 on 2024-01-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0010_alter_video_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='drive_link',
            field=models.TextField(blank=True),
        ),
    ]
